#!/bin/bash

# Variables
DIR_NAME=$1
SESSION_NAME=$(tmux display-message -p "#S")
CURRENT_INDEX=$(tmux display-message -p "#I")

tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.1 'dev' C-m
tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.1 "cd $DIR_NAME/backend" C-m
tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.1 'source venv/bin/activate' C-m
tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.1 'python manage.py runserver' C-m

tmux split-window -h -t $SESSION_NAME:$CURRENT_INDEX

tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.2 'dev' C-m
tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.2 "cd $DIR_NAME/frontend" C-m
tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.2 'npm run dev' C-m

tmux split-window -v -t $SESSION_NAME:$CURRENT_INDEX

tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.3 'dev' C-m
tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.3 "cd $DIR_NAME/frontend" C-m

tmux split-window -v -t $SESSION_NAME:$CURRENT_INDEX.1

tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.2 'dev' C-m
tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.2 "cd $DIR_NAME/backend" C-m
tmux send-keys -t $SESSION_NAME:$CURRENT_INDEX.2 'source venv/bin/activate' C-m

NEW_INDEX=$(tmux new-window -t $SESSION_NAME -P -F "#{window_index}")

tmux send-keys -t $SESSION_NAME:$NEW_INDEX 'dev' C-m
tmux send-keys -t $SESSION_NAME:$NEW_INDEX "cd $DIR_NAME/frontend" C-m
tmux send-keys -t $SESSION_NAME:$NEW_INDEX 'vim .' C-m

tmux rename-session -t $SESSION_NAME $DIR_NAME
